### ISSUE TITLE
add more languages.

### ISSUE THREAD

**Issue by imposter361** [aedangaming/DNS-Changer#2]
Sometimes the keyboard is not set to English and it's annoying that it doesn't accept the command!
Please fix this!
For example, when we press the "C" key, the letter "ز" is written in Persian!
You can make "ز" equal to "C" or make it write "C" in any language when the "C" button is pressed!

**Comment by m-ehsan** [comment]
Resolved at efa24d36b1819a2f90d9c5bd12cfbc7720a67a03
@imposter361, thanks for your great feature request 🙏
